// Code generated by Kitex v0.3.4. DO NOT EDIT.

package aggregateddiscoveryservice

import (
	server "github.com/cloudwego/kitex/server"
	"github.com/kitex-contrib/xds/core/api/kitex_gen/envoy/service/discovery/v3"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler v3.AggregatedDiscoveryService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
