// Code generated by Kitex v0.3.4. DO NOT EDIT.
package aggregateddiscoveryservice

import (
	server "github.com/cloudwego/kitex/server"
	"github.com/kitex-contrib/xds/core/api/kitex_gen/envoy/service/discovery/v3"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler v3.AggregatedDiscoveryService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
