// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: ads.proto

package v3

import (
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	v3discovery "github.com/envoyproxy/go-control-plane/envoy/service/discovery/v3"
)

// Code generated by Kitex v0.3.4. DO NOT EDIT.

type AggregatedDiscoveryService interface {
	StreamAggregatedResources(stream AggregatedDiscoveryService_StreamAggregatedResourcesServer) (err error)
	DeltaAggregatedResources(stream AggregatedDiscoveryService_DeltaAggregatedResourcesServer) (err error)
}

type AggregatedDiscoveryService_StreamAggregatedResourcesServer interface {
	streaming.Stream
	Recv() (*v3discovery.DiscoveryRequest, error)
	Send(*v3discovery.DiscoveryResponse) error
}

type AggregatedDiscoveryService_DeltaAggregatedResourcesServer interface {
	streaming.Stream
	Recv() (*v3discovery.DeltaDiscoveryRequest, error)
	Send(*v3discovery.DeltaDiscoveryResponse) error
}
